<a href="https://colab.research.google.com/github/JenClifford/DataCleaningPython/blob/main/DescriptiveStatistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([5, 3, 7])
print(a)


[5 3 7]


In [ ]:
import numpy as np
b = np.array([[2, 4, 6], [3, 5, 7]])
print(b)

[[2 4 6]
 [3 5 7]]


In [ ]:
!pip install sqlalchemy --upgrade
from sqlalchemy import create_engine, text
import pandas as pd
from scipy import stats

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 11.3 MB/s eta 0:00:00
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.5.0
    Uninstalling typing_extensions-4.5.0:
      Successfully uninstalled typing_extensions-4.5.0
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.24
    Uninstalling SQLAlchemy-2.0.24:
      Successfully uninstalled SQLAlchemy-2.0.24
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.9.0 which is incompatible.


In [ ]:
postgres_user = 'dabc_student'
postgres_pw = '7*.8G9QH21'
postgres_host = '142.93.121.174'
postgres_port = '5432'
postgres_db = 'kickstarterprojects'
engine = create_engine('postgresql://{}:{}@{}:{}/{}'.format(
    postgres_user, postgres_pw, postgres_host, postgres_port, postgres_db))

In [ ]:
projects_df = pd.read_sql_query(text('SELECT * FROM ksprojects'), con=engine.connect())
engine.dispose()

In [ ]:
projects_df.shape

(65418, 13)

In [ ]:
projects_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65418 entries, 0 to 65417
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   id             65418 non-null  int64         
 1   name           65418 non-null  object        
 2   category       65418 non-null  object        
 3   main_category  65418 non-null  object        
 4   deadline       65418 non-null  datetime64[ns]
 5   goal           65418 non-null  float64       
 6   launched       65418 non-null  datetime64[ns]
 7   state          65418 non-null  object        
 8   backers        65418 non-null  int64         
 9   country        65418 non-null  object        
 10  usd_pledged    64673 non-null  float64       
 11  currency       65418 non-null  object        
 12  pledged        65418 non-null  float64       
dtypes: datetime64[ns](2), float64(3), int64(2), object(6)
memory usage: 6.5+ MB


In [ ]:
projects_df.head()

id                                               name  \
0  1147015301  "All We Had" Gets Into Cannes -- $10 or More G...   
1  1100844465                                       daily digest   
2  1316334968                             Drive A Faster Car 2.0   
3  1304906577         Accidental to Edinburgh - PHASE 1: AIRFARE   
4  1099226462          Logical Guess Pictures' 2nd Horror Movie!   

       category main_category            deadline    goal            launched  \
0   Documentary  Film & Video 2009-05-20 21:50:00   300.0 2009-04-30 22:10:30   
1   Documentary  Film & Video 2009-06-01 02:20:00   700.0 2009-05-04 21:14:28   
2    Nonfiction    Publishing 2009-06-04 06:00:00  1000.0 2009-05-04 22:51:31   
3       Theater       Theater 2009-06-05 05:59:00  6000.0 2009-04-30 22:22:43   
4  Film & Video  Film & Video 2009-06-06 00:45:00   500.0 2009-04-30 01:32:55   

        state  backers country  usd_pledged currency  pledged  
0      failed        4      US        40.00      USD    40.00  
1  successful       14      US       700.00      USD   700.00  
2  successful       32      US      1367.00      USD  1367.00  
3  successful       24      US      6575.00      USD  6575.00  
4  successful       22      US       501.66      USD   501.66

In [ ]:
projects_df['category'].nunique()

158

In [ ]:
category_counts = projects_df['category'].value_counts()
category_counts.head(10)

Product Design    3444
Documentary       2969
Music             2740
Shorts            2407
Tabletop Games    2208
Food              2126
Video Games       2011
Film & Video      1828
Fiction           1670
Fashion           1584
Name: category, dtype: int64

In [ ]:
projects_df['main_category'].nunique()

15

In [ ]:
projects_df['country'].nunique()

NameError: name 'projects_df' is not defined

In [ ]:
print(projects_df.size)

850434


In [ ]:
clean_projects = projects_df.dropna()

In [ ]:
print(clean_projects.size)

840749


In [ ]:
def series_statistics(column):
  print('statistics for column: {}'.format(column.name))
  print('The max value in the column: {}'.format(column.max()))
  print('The min value in the column: {}'.format(column.min()))
  print('The mode value in the column: {}'.format(column.mode()))
  print('The median value in the column: {}'.format(column.median()))
  print('The mean of the column: {}'.format(column.mean()))
  print('The std of the column: {}'.format(column.std()))


In [ ]:
series_statistics(clean_projects['goal'])

statistics for column: goal
The max value in the column: 100000000.0
The min value in the column: 1.0
The mode value in the column: 0    5000.0
Name: goal, dtype: float64
The median value in the column: 5000.0
The mean of the column: 42094.83745674393
The std of the column: 1033205.273898726


In [ ]:
series_statistics(clean_projects['usd_pledged'])


statistics for column: usd_pledged
The max value in the column: 8596480.0
The min value in the column: 0.0
The mode value in the column: 0    0.0
Name: usd_pledged, dtype: float64
The median value in the column: 542.0
The mean of the column: 7900.242114883228
The std of the column: 72783.34386005609


In [ ]:
clean_projects['goal'].describe()


count    6.467300e+04
mean     4.209484e+04
std      1.033205e+06
min      1.000000e+00
25%      2.000000e+03
50%      5.000000e+03
75%      1.500000e+04
max      1.000000e+08
Name: goal, dtype: float64

In [ ]:
clean_projects['usd_pledged'].describe()

count    6.467300e+04
mean     7.900242e+03
std      7.278334e+04
min      0.000000e+00
25%      2.500000e+01
50%      5.420000e+02
75%      3.608380e+03
max      8.596480e+06
Name: usd_pledged, dtype: float64

In [ ]:
clean_projects[['goal', 'usd_pledged', 'backers']].describe()

goal   usd_pledged        backers
count  6.467300e+04  6.467300e+04   64673.000000
mean   4.209484e+04  7.900242e+03     104.336091
std    1.033205e+06  7.278334e+04     994.725411
min    1.000000e+00  0.000000e+00       0.000000
25%    2.000000e+03  2.500000e+01       2.000000
50%    5.000000e+03  5.420000e+02      13.000000
75%    1.500000e+04  3.608380e+03      56.000000
max    1.000000e+08  8.596480e+06  154926.000000

In [ ]:
clean_projects['goal'].corr(clean_projects['usd_pledged'])

0.006423740131433384

In [ ]:
clean_projects[['goal', 'usd_pledged', 'backers']].corr()

goal  usd_pledged   backers
goal         1.000000     0.006424  0.003033
usd_pledged  0.006424     1.000000  0.569047
backers      0.003033     0.569047  1.000000

In [ ]:
# Database credentials
postgres_user = 'dabc_student'
postgres_pw = '7*.8G9QH21'
postgres_host = '142.93.121.174'
postgres_port = '5432'
postgres_db = 'baseball'

In [ ]:
engine = create_engine('postgresql://{}:{}@{}:{}/{}'.format(
    postgres_user, postgres_pw, postgres_host, postgres_port, postgres_db))


In [ ]:
sql = 'SELECT p.playerid, birthyear, birthcountry, deathyear, namefirst, namelast, weight, height, bats, throws, yearid, teamid, lgid, salary FROM people p join salaries s on p.playerid = s.playerid'


In [ ]:
players_df = pd.read_sql_query(text(sql), con=engine.connect())


In [ ]:
engine.dispose()

In [ ]:
players_df.head(2)

playerid  birthyear birthcountry  deathyear namefirst   namelast  weight  \
0  barkele01       1955          USA        NaN       Len     Barker     225   
1  bedrost01       1957          USA        NaN     Steve  Bedrosian     200   

   height bats throws  yearid teamid lgid  salary  
0      77    R      R    1985    ATL   NL  870000  
1      75    R      R    1985    ATL   NL  550000

In [ ]:
players_1990 = players_df.iloc[(players_df['yearid'] == 1990).values]
players_1990.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 867 entries, 3289 to 4155
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   playerid      867 non-null    object 
 1   birthyear     867 non-null    int64  
 2   birthcountry  867 non-null    object 
 3   deathyear     36 non-null     float64
 4   namefirst     867 non-null    object 
 5   namelast      867 non-null    object 
 6   weight        867 non-null    int64  
 7   height        867 non-null    int64  
 8   bats          867 non-null    object 
 9   throws        867 non-null    object 
 10  yearid        867 non-null    int64  
 11  teamid        867 non-null    object 
 12  lgid          867 non-null    object 
 13  salary        867 non-null    int64  
dtypes: float64(1), int64(5), object(8)
memory usage: 101.6+ KB


In [ ]:
players_2000 = players_df.iloc[(players_df['yearid'] == 2000).values]
players_2000.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 836 entries, 12263 to 13098
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   playerid      836 non-null    object 
 1   birthyear     836 non-null    int64  
 2   birthcountry  836 non-null    object 
 3   deathyear     10 non-null     float64
 4   namefirst     836 non-null    object 
 5   namelast      836 non-null    object 
 6   weight        836 non-null    int64  
 7   height        836 non-null    int64  
 8   bats          836 non-null    object 
 9   throws        836 non-null    object 
 10  yearid        836 non-null    int64  
 11  teamid        836 non-null    object 
 12  lgid          836 non-null    object 
 13  salary        836 non-null    int64  
dtypes: float64(1), int64(5), object(8)
memory usage: 98.0+ KB


In [ ]:
stats.ttest_ind(players_1990['salary'], players_2000['salary'])

TtestResult(statistic=-16.90651573407297, pvalue=2.1593870550905857e-59, df=1701.0)

In [ ]:
sample_1_n = players_1990.shape[0]
sample_2_n = players_2000.shape[0]
sample_1_mean = players_1990['salary'].mean()
sample_2_mean = players_2000['salary'].mean()
sample_1_var = players_1990['salary'].var()
sample_2_var = players_2000['salary'].var()

In [ ]:
import math
std_err_difference = math.sqrt((sample_1_var/sample_1_n)+(sample_2_var/sample_2_n))

mean_difference = sample_2_mean - sample_1_mean

margin_of_error = 1.96 * std_err_difference
ci_lower = mean_difference - margin_of_error
ci_upper = mean_difference + margin_of_error

print("The difference in means at the 95% confidence interval is between "+str(ci_lower)+" and "+str(ci_upper)+".")

The difference in means at the 95% confidence interval is between 1306451.0963904148 and 1655570.6584535998.


In [ ]:
def get_95_ci(array_1, array_2):
    sample_1_n = array_1.shape[0]
    sample_2_n = array_2.shape[0]
    sample_1_mean = array_1.mean()
    sample_2_mean = array_2.mean()
    sample_1_var = array_1.var()
    sample_2_var = array_2.var()
    mean_difference = sample_2_mean - sample_1_mean
    std_err_difference = math.sqrt((sample_1_var/sample_1_n)+(sample_2_var/sample_2_n))
    margin_of_error = 1.96 * std_err_difference
    ci_lower = mean_difference - margin_of_error
    ci_upper = mean_difference + margin_of_error
    return("The difference in means at the 95% confidence interval (two-tail) is between "+str(ci_lower)+" and "+str(ci_upper)+".")

get_95_ci(players_1990['salary'],players_2000['salary'])

'The difference in means at the 95% confidence interval (two-tail) is between 1306451.0963904148 and 1655570.6584535998.'